version: "3"
services:
  database:
    container_name: database
    hostname: database
    image: mysql
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    ports:
      - 3306:3306
    restart: unless-stopped
  flask:
    container_name: flask
    hostname: flask
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "9000:9000"
    depends_on:
      - database
    restart: always
